#! /bin/bash

BRANCH=$( git branch | grep '*' | sed -r 's/^\s*\*\s+(\S+)$/\1/' )

if [[ $BRANCH = "master" ]]
then
  # Re-enable if/once migrated to new Twitter API plan
  python create_tweets.py
else
  python create_tweets.py
fi

