#! /bin/bash

#####################################################################
# Per https://sharats.me/posts/shell-script-best-practices/ (partial)
set -o errexit
set -o nounset
set -o pipefail

if [[ "${TRACE-0}" == "1" ]]; then
    set -o xtrace
fi
#####################################################################

cd data
zip -m eps.json.zip eps*.json
zip -m rss.json.zip rss.json
zip -m new_upd_pkgs.json.zip new_upd_pkgs.json
