#! /bin/bash

DATA_FILE="data/f8.list"
LOG_FILE="data/gen.log"

dstamp () {
  date -uIsec | grep -Eo '.*[+]'
}

log () {
  echo "$( dstamp )  $1" >> $LOG_FILE
}


# Remove any existing generation log
if [[ -e "$LOG_FILE" ]]
then
  echo "Removing old log"
  rm "$LOG_FILE"
fi

# Restart the entry points JSON
python eps_json.py init --restart
log "JSON Restarted"

# Loop over all the indicated packages
for pkg in $( cat $DATA_FILE )
do
  log "====== Start $pkg"

  # Install the package from PyPI w/o dependencies
  log "---- Attempt install"

  pip install --no-deps $pkg

  install_result=$?
  if [[ $install_result -eq 0 ]]
  then
    log ".. OK"
  else
    log ".. FAILED (exit $install_result)"
  fi

  # Run the entry points JSON recorder if install worked
  if [[ $install_result -eq 0 ]]
  then
    log "---- Attempt entry point retrieval"
    python eps_json.py $pkg

    json_result=$?
    if [[ $json_result -eq 0 ]]
    then
      log ".. OK"
    else
      log ".. FAILED (exit $json_result)"
    fi

  else
    log "---- SKIP entry point retrieval"
  fi

  # Uninstall the package, regardless of whether install succeeded
  log "---- Uninstall package"

  # flufl-flake8 installs as flufl.flake8
  # Always try to remove it
  pip uninstall -y $pkg flufl.flake8

  uninst_result=$?

  if [[ $uninst_result -eq 0 ]]
  then
    log ".. OK"
  else
    log ".. CRITICAL (exit $uninst_result), invalid state! Halting!"
    exit 1
  fi

done


log "====== DONE"

exit 0

