#! /bin/bash

BRANCH=$( git branch | grep '*' | sed -r 's/^\s*\*\s+(\S+)$/\1/' )

if [[ $BRANCH = "master" ]]
then
  git add . && git commit -m "Update content - $( date -uIs )"
  if [[ $? -eq 0 ]]
  then
    git push https://bskinn@github.com/bskinn/list-of-flake8-entrypoints
  fi
else
  echo "Not on master branch; skipping repo commit."
fi

