#! /bin/bash

BRANCH=$( git branch | grep '*' | sed -r 's/^\s*\*\s+(\S+)$/\1/' )

if [[ $BRANCH -eq master ]]
then
  git add . && git commit -m "Update content - $( date -uIs )" && git push https://bskinn:$COMMIT_TOKEN@github.com/bskinn/list-of-flake8-entrypoints
fi

