name: Update repo flake8 entry_points data

on:
  push:
    branches-ignore:
      # Because master will be scheduled
      - master
      - noaction-*
      - upgrade-2023  # Until the pkg-ID/tweet/RSS refactor is done
  schedule:
    - cron: '11 10 * * *'
  workflow_dispatch:
    inputs:
      trace:
        description: 'Debug trace (0=off, 1=on)'
        type: choice
        default: '0'
        required: true
        options:
        - '0'
        - '1'


defaults:
  run:
    shell: bash

env:
  TRACE: ${{ inputs.trace }}

jobs:
  update_f8eps:
    name: Update flake8 entry_points data
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"

    steps:
    - name: Check out repo
      uses: actions/checkout@v3

    - name: Install Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'
        cache-dependency-path: |
          requirements.txt
          data/f8.list

    - name: Install dependencies & report
      run: ./catcall ./10-install-dependencies

    - name: Clear build, rename/copy data
      run: ./catcall ./20-prepare-files

    - name: Retrieve filtered package list
      run: ./catcall ./30-retrieve-package-data

    - name: Generate the entry-points JSON and report
      run: ./catcall ./40-generate-eps-json

    - name: Render the markdown
      run: ./catcall ./50-render-markdown

    - name: Post tweets, if on master
      env:
        F8_TWITTER_KEY: ${{ secrets.F8_TWITTER_KEY }}
        F8_TWITTER_SECRET_KEY: ${{ secrets.F8_TWITTER_SECRET_KEY }}
        F8_TWITTER_TOKEN: ${{ secrets.F8_TWITTER_TOKEN }}
        F8_TWITTER_SECRET_TOKEN: ${{ secrets.F8_TWITTER_SECRET_TOKEN }}
      run: ./catcall ./60-post-tweets

    - name: Generate RSS feed
      run: ./catcall ./70-create-feed

    - name: Cull old files
      run: ./catcall ./80-cull-old-files

    - name: Zip the JSON
      run: ./catcall ./90-package-json

    - name: Report workspace git status
      run: ./catcall ./a0-report-git-status

    - name: Commit updated files back to repo
      run: ./catcall ./b0-repo-commit

