name: Update repo flake8 entry_points data

on:
  push:
    branches-ignore:
      # Because master will be scheduled
      - master
      - noaction-*
  schedule:
    - cron: '11 10 * * *'

defaults:
  run:
    shell: bash

jobs:
  update_f8eps:
    name: Update flake8 entry_points data
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"

    steps:
    - name: Check out repo
      uses: actions/checkout@v2

    - name: Install Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies & report
      run: ./catcall ./10-install-dependencies

    - name: Clear build, rename/copy data
      run: ./catcall ./20-prepare-files

    - name: Retrieve filtered package list
      run: ./catcall ./30-retrieve-package-data

    - name: Generate the entry-points JSON and report
      run: ./catcall ./40-generate-eps-json

    - name: Render the markdown
      run: ./catcall ./50-render-markdown

    - name: Post tweets, if on master
      env:
        F8_TWITTER_KEY: ${{ secrets.F8_TWITTER_KEY }}
        F8_TWITTER_SECRET_KEY: ${{ secrets.F8_TWITTER_SECRET_KEY }}
        F8_TWITTER_TOKEN: ${{ secrets.F8_TWITTER_TOKEN }}
        F8_TWITTER_SECRET_TOKEN: ${{ secrets.F8_TWITTER_SECRET_TOKEN }}
      run: ./catcall ./60-post-tweets

    - name: Generate RSS feed
      run: ./catcall ./70-create-feed

    - name: Cull old files
      run: ./catcall ./80-cull-old-files

    - name: Zip the JSON
      run: ./catcall ./90-package-json

    - name: Report workspace git status
      run: ./catcall ./a0-report-git-status

    - name: Commit updated files back to repo
      run: ./catcall ./b0-repo-commit

