name: Update repo flake8 entry_points data

on:
  push:
    branches-ignore:
      # Because master will be scheduled
      - master
      - noaction-*
  schedule:
    - cron: '11 10 * * *'
  workflow_dispatch:
    inputs:
      trace:
        description: 'Debug trace (0=off, 1=on)'
        type: choice
        default: '0'
        required: true
        options:
        - '0'
        - '1'


defaults:
  run:
    shell: bash

env:
  TRACE: ${{ inputs.trace }}

jobs:
  update_f8eps:
    name: Update flake8 entry_points data
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"

    steps:
    - name: Check out repo
      uses: actions/checkout@v3

    - name: Install Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'
        cache-dependency-path: |
          requirements.txt
          data/f8.list

    - name: Install dependencies & report
      run: ./catcall.sh ./10-install-dependencies.sh

    - name: Clear build, rename/copy data
      run: ./catcall.sh ./20-prepare-files.sh

    - name: Retrieve filtered package list
      run: ./catcall.sh ./30-retrieve-package-data.sh

    - name: Generate the entry-points JSON and report
      run: ./catcall.sh ./40-generate-eps-json.sh

    - name: Render the markdown
      run: ./catcall.sh ./50-render-markdown.sh

    - name: Post tweets, if on master
      env:
        F8_TWITTER_KEY: ${{ secrets.F8_TWITTER_KEY }}
        F8_TWITTER_SECRET_KEY: ${{ secrets.F8_TWITTER_SECRET_KEY }}
        F8_TWITTER_TOKEN: ${{ secrets.F8_TWITTER_TOKEN }}
        F8_TWITTER_SECRET_TOKEN: ${{ secrets.F8_TWITTER_SECRET_TOKEN }}
      run: ./catcall.sh ./60-post-tweets.sh

    - name: Generate RSS feed
      run: ./catcall.sh ./70-create-feed.sh

    - name: Cull old files
      run: ./catcall.sh ./80-cull-old-files.sh

    - name: Zip the JSON
      run: ./catcall.sh ./90-package-json.sh

    - name: Report workspace git status
      run: ./catcall.sh ./a0-report-git-status.sh

    - name: Commit updated files back to repo
      run: ./catcall.sh ./b0-repo-commit.sh
