name: Update repo flake8 entry_points data

on:
  push:
    branches-ignore:
      # Because master will be scheduled
      - master
      - noaction-*
  schedule:
    - cron: '11 10 * * 2,5'

defaults:
  run:
    shell: bash

jobs:
  update_f8eps:
    name: Update flake8 entry_points data
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2

    - name: Install Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies & report
      run: |
        python -m pip install -U pip
        pip install -r requirements.txt
        pip list

    - name: Clear build, rename data
      run: |
        rm -f mdbuild/*
        cd data
        mv f8.list f8.list.old
        unzip eps.json.zip
        rm eps.json.zip
        mv eps_ext.json eps_ext.json.old
        mv eps_rep.json eps_rep.json.old

    - name: Retrieve filtered package list
      run: |
        python f8_list.py
        cat data/f8.list | tr '\n' '  '

    - name: Generate the entry-points JSON and report
      run: |
        ./generate_eps_json || ( cat data/gen.log; exit 1 )
        head -c80 data/*.json

    - name: Render the markdown
      run: |
        python write_content.py
        head -n20 mdbuild/*.md

    - name: Cull old files
      run: rm data/*.old

    - name: Zip the JSON
      run: |
        cd data
        zip -m eps.json.zip *.json

    - name: Report workspace git status
      run: |
        git status
        git branch -vv

    - name: Commit updated files back to repo
      env:
        COMMIT_TOKEN: ${{ secrets.COMMIT_TOKEN }}
      run: |
        git config user.name "Brian Skinn"
        git config user.email "brian.skinn@gmail.com"
        ./repo_commit
